
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Identificateur", targetNamespace = "http://ferhi.com/identification", wsdlLocation = "http://localhost:8585/Identificateur?WSDL")
public class Identificateur_Service
    extends Service
{

    private final static URL IDENTIFICATEUR_WSDL_LOCATION;
    private final static WebServiceException IDENTIFICATEUR_EXCEPTION;
    private final static QName IDENTIFICATEUR_QNAME = new QName("http://ferhi.com/identification", "Identificateur");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/Identificateur?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTIFICATEUR_WSDL_LOCATION = url;
        IDENTIFICATEUR_EXCEPTION = e;
    }

    public Identificateur_Service() {
        super(__getWsdlLocation(), IDENTIFICATEUR_QNAME);
    }

    public Identificateur_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTIFICATEUR_QNAME, features);
    }

    public Identificateur_Service(URL wsdlLocation) {
        super(wsdlLocation, IDENTIFICATEUR_QNAME);
    }

    public Identificateur_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTIFICATEUR_QNAME, features);
    }

    public Identificateur_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Identificateur_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Identificateur
     */
    @WebEndpoint(name = "IdentificateurPort")
    public Identificateur getIdentificateurPort() {
        return super.getPort(new QName("http://ferhi.com/identification", "IdentificateurPort"), Identificateur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Identificateur
     */
    @WebEndpoint(name = "IdentificateurPort")
    public Identificateur getIdentificateurPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ferhi.com/identification", "IdentificateurPort"), Identificateur.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTIFICATEUR_EXCEPTION!= null) {
            throw IDENTIFICATEUR_EXCEPTION;
        }
        return IDENTIFICATEUR_WSDL_LOCATION;
    }

}
