
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Identificateur", targetNamespace = "http://ferhi.com/identification")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Identificateur {


    /**
     * 
     * @param identifiant
     * @return
     *     returns service.Personne
     */
    @WebMethod
    @WebResult(name = "personne", targetNamespace = "http://ferhi.com/identification")
    @RequestWrapper(localName = "getPersonne", targetNamespace = "http://ferhi.com/identification", className = "service.GetPersonne")
    @ResponseWrapper(localName = "getPersonneResponse", targetNamespace = "http://ferhi.com/identification", className = "service.GetPersonneResponse")
    @Action(input = "http://ferhi.com/identification/Identificateur/getPersonneRequest", output = "http://ferhi.com/identification/Identificateur/getPersonneResponse")
    public Personne getPersonne(
        @WebParam(name = "identifiant", targetNamespace = "http://ferhi.com/identification")
        int identifiant);

    /**
     * 
     * @param personne
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "identifiant", targetNamespace = "http://ferhi.com/identification")
    @RequestWrapper(localName = "getIdentifiant", targetNamespace = "http://ferhi.com/identification", className = "service.GetIdentifiant")
    @ResponseWrapper(localName = "getIdentifiantResponse", targetNamespace = "http://ferhi.com/identification", className = "service.GetIdentifiantResponse")
    @Action(input = "http://ferhi.com/identification/Identificateur/getIdentifiantRequest", output = "http://ferhi.com/identification/Identificateur/getIdentifiantResponse")
    public int getIdentifiant(
        @WebParam(name = "personne", targetNamespace = "http://ferhi.com/identification")
        Personne personne);

}
