
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculateur", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculateur {


    /**
     * 
     * @param operand1
     * @param operand2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://service/", className = "service.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://service/", className = "service.MultiplyResponse")
    @Action(input = "http://service/Calculateur/multiplyRequest", output = "http://service/Calculateur/multiplyResponse")
    public double multiply(
        @WebParam(name = "operand1", targetNamespace = "")
        double operand1,
        @WebParam(name = "operand2", targetNamespace = "")
        double operand2);

    /**
     * 
     * @param operand1
     * @param operand2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service/", className = "service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service/", className = "service.AddResponse")
    @Action(input = "http://service/Calculateur/addRequest", output = "http://service/Calculateur/addResponse")
    public double add(
        @WebParam(name = "operand1", targetNamespace = "")
        double operand1,
        @WebParam(name = "operand2", targetNamespace = "")
        double operand2);

}
